ports:
  - port: 8000
    onOpen: open-browser

tasks:
  - init: >
      pip3 install --upgrade pip &&
      pip3 install -r reequirements.txt && 
      django-admin startproject config . &&
      echo "ALLOWED_HOSTS = ['*']" >> settings.py &&
      python3 manage.py migrate
    command: python3 manage.py runserver
